### ISSUE TITLE
After disabling nether_prisons simple portal to nether don't work

### ISSUE THREAD

**Issue by amadin** [HybridDog/nether-pack#1]
After changing local nether_prisons = minetest.setting_getbool("enable_damage") to this:
local nether_prisons = nil
or commenting this strind simple portal to nether on the ground don't work.

**Comment by HybridDog** [comment]
the obsidian one only leads to the nether, there are other ways to get there which make more sense

**Comment by amadin** [comment]
I think you don't undestand me right. I mean i can't go in nether because portal does not activate.

**Comment by HybridDog** [comment]
sorry, l somehow missed a few words

> the obsidian one only [works if nether_prisons is enabled], [else] there are other ways to get there which make more sense [, e.g. adding a global travelnet station there (players can place their own in the nether too)]

**Comment by amadin** [comment]
:( 
Too bad for me, then i have to install of Pilzadam's nether mod + subterrain mod although it is generate map slower.

**Comment by HybridDog** [comment]
When l played on a server, l noticed that PilzAdam's portal gets added even if there's a house. So if someone activates a portal in the nether and someone's house is at the other side, the portal appears there even if it's protected. I think it can be used for grieving purposes, l'm not sure, l haven't activated one for a long time.

**Comment by amadin** [comment]
I thinked about this before. If player activated new portal in nether the portal must not appears at the other side, just teleport player.

**Comment by HybridDog** [comment]
l'm currently trying to generate the world before teleporting there to be able to find a position where the player can stand and where's air which can be replaced by a portal.
If the area is protected or solid nodes are there, should the portal height be increased until there's free space?

**Comment by amadin** [comment]
If you ask about on the ground area (not nether) i think players will not like see someone's portal over his house. But you can increase portal height until there's free space in nether (if anybody builded and protected his house in nether) i think.

**Comment by HybridDog** [comment]
l think flying portals don't look good.

**Comment by amadin** [comment]
For nether underground flying portal is not bad because this is another world. If no other way to appear a portal without destroying houses.

**Comment by Desour** [comment]
Can't reproduce the original reason for this issue.
