### ISSUE TITLE
Nether guide overlapping text

### ISSUE THREAD

**Issue by HybridDog** [HybridDog/nether-pack#10]
The nether guide is broken, text shouldn't overlap:
![screenshot_20171225_214055](https://user-images.githubusercontent.com/3192173/34342818-7724d086-e9bc-11e7-938c-6114776b1f56.png)
Maybe [containers](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1898) can be used to fix this problem.

**Comment by HybridDog** [comment]
fixed

**Comment by Desour** [comment]
Bei der "Portal" Seite ist der Text bei mir unten etwas abgeschnitten:
![screenshot_20220820_220356](https://user-images.githubusercontent.com/7613443/185764338-e9a203bb-7f1e-432d-a9bc-8c52c2192c12.png)

**Comment by HybridDog** [comment]
ganz nach unten gescrollt sollte das nicht passieren.
