### ISSUE TITLE
The required portal structure is asymmetric because of a bug in is_netherportal

### ISSUE THREAD

**Issue by Orisphera** [HybridDog/nether-pack#13]
Disclaimer: I probably may determine if something is a bug incorrectly. I know some things in a similar game that they say make no sense, although they make perfect sense to me. But it's possible that this one is indeed a bug, so I'll report it.

Note: In this report, I'm talking about the portal that one uses to get out of the Nether and to get back with items from Overworld and not obsidian portals.

# Background

It seems like something removed the reference image for a portal from the wiki. I was curious, so I've looked for it in the code. It uses the function

```
-- a not filled square
local function vector_square(r)
	local tab, n = {}, 1
	for i = -r+1, r do
		for j = -1, 1, 2 do
			local a, b = r*j, i*j
			tab[n] = {a, b}
			tab[n+1] = {b, a}
			n=n+2
		end
	end
	return tab
end
```

I think there's a bug in this code. So, I tested it and found that it indeed results in weird behavior.

# Effect

It checks for the northeastern and southwestern corners, but not for the northwestern and southeastern ones.

# Cause

The outer `for` starts from `-r+1` rather than `-r`. You probably did that to avoid checking for the corners twice. However, because of a mistake in the implementation, this still checks for them twice, but only checks for two of them.

Note: If the upper bound was somehow exclusive in this case, this would be symmetrical. It would not check for any corners in this case. I couldn't find any sources that explied that Lua `for` loop was inclusive. However, a lot of other code, including the inner loop here, wouldn't work if it wasn't.

# Fix

I have two easy ways of fixing this. One is by removing the `+1`. Here, it would check for the corners twice, but that's not a big deal. The other one is by inserting `-` in one (or three) of the following places:

```
			tab[n] = {[-]a, [-]b}
			tab[n+1] = {[-]b, [-]a}
```

**Comment by HybridDog** [comment]
Thanks for the detailed bug report.
I've applied the fix which adds a `-`.

> It seems like something removed the reference image for a portal from the wiki.

Which wiki do you mean?

The reference image in the in-game nether guide (`/nether_help` chat command) still works for me.
![2023-10-30-175936_929x826_scrot](https://github.com/HybridDog/nether-pack/assets/3192173/95baa680-3f61-418c-8680-b350f23ec635)
