### ISSUE TITLE
nether stones aren't digable in creative with bare hand

### ISSUE THREAD

**Issue by Desour** [HybridDog/nether-pack#3]
Maybe that could be changed by overriding the wieldhand if creative is enabled.
To do or not to do?

**Comment by BetterToAutomateTheWorld** [comment]
Add this feature is a good idea, i hope it will be made soon :)

**Comment by Desour** [comment]
PR started: #4

**Comment by HybridDog** [comment]
<ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt>
<ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt>
<ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt>
<ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt>
<ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt>
<ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt><ruby><rt>sieh mal, wo ich hier bin!
</rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby>
</rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby>
</rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby>
</rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby>
</rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby>
</rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby></rt></ruby> </rt></ruby> </rt></ruby>
