### ISSUE TITLE
suggestion: make pearl to particle

### ISSUE THREAD

**Issue by Desour** [HybridDog/nether-pack#5]

**Comment by HybridDog** [comment]
<ruby>Die Perle sollte auch in ungeladenem Gebiet funktionieren.<rt><img src="http://estepona-katzen.de/wp/wp-content/uploads/2017/06/angel2-753x1024.jpg" widtdh="99999" hedight="50" vspace="0" hspace="674" alignd="right" />
</rt></ruby>

**Comment by Desour** [comment]
>Die Perle sollte auch in ungeladenem Gebiet funktionieren.<details><summary>miez</summary>![miez](http://estepona-katzen.de/wp/wp-content/uploads/2017/06/angel2-753x1024.jpg)</details>

Ooh, Miez. :3
Ja, klar, aber man könnte doch die Parabellaufbahn herausfinden und dann die expirationtime so setzen, dass sie verschwindet, wenn sie aufprallt. Die ungeladenen gebiete kann man ja dafür mit voxelmanipulation einmal laden.

**Comment by HybridDog** [comment]
Ja, wenn man minetest.after benutzt ist sogar das Problem gelöst mit den alten Perlen, die irgendwann plötzlich.
